---
# tasks file for roles/php-ubuntu
- name: install php
  apt:
    name:
      - php
      - php-mysql
      - libapache2-mod-php
    state: latest
    update_cache: yes

- name: php index host
  copy:
    content: "leechongwei"
    dest: /var/www/html/index2.html
    owner: root
    group: root
    mode: '0644'
