---
# tasks file for roles/nagios_plugins
- name: install nagios plugins
  unarchive:
    src: https://nagios-plugins.org/download/nagios-plugins-2.3.3.tar.gz
    dest: /tmp
    remote_src: yes

- name: configure nagios plugins
  command: ./configure --with-nagios-user=nagios --with-nagios-group=nagcm
  args:
    chdir: /tmp/nagios-plugins-2.3.3

- name: configure by make
  make:
    chdir: /tmp/nagios-plugins-2.3.3

- name: configure by make install
  make:
    target: install
    chdir: /tmp/nagios-plugins-2.3.3

- name: enable and start nagios
  service:
    name: nagios
    enabled: yes
    state: started
