---
- name: install elastic in ubuntu
  hosts: ubuntu
  roles:
    - elastic1

- name: install nagios in ubuntu
  hosts: ubuntu
  vars_files:
    - ./config.yaml
  roles:
    - configure_ubuntu
    - nagiosmain
    - nagios_plugins

- name: install grafana, prometheus, influxdb in ubuntu
  hosts: ubuntu
  roles:
    - grafana-1

- name: install lamp in ubuntu
  hosts: ubuntu
  roles:
    - apache2-ubuntu
    - mysql-ubuntu
    - php-ubuntu
    - web-service1
