---
# tasks file for roles/mysql-ubuntu
- name: install mysql server
  apt:
    name: mysql-server
    state: latest
    update_cache: yes

- name: mysql host index
  copy:
    content: "qtsbautista"
    dest: /var/www/html/index1.html
    owner: root
    group: root
    mode: '0644'
  register: mysql_index1

- name: start and enable mysql server
  service:
    name: mysql
    state: restarted
    enabled: yes
  when: mysql_index1
