---
# tasks file for roles/nagiosmain
- name: download and extract nagios core
  unarchive:
    src: https://assets.nagios.com/downloads/nagioscore/releases/nagios-4.4.5.tar.gz
    dest: /tmp
    copy: no

- name: configure nagios using ubuntu
  command: ./configure --with-nagios-group=nagcmd --with-command-group=nagcmd --with-httpd_conf=/etc/apache2/sites-enabled
  args:
    chdir: /tmp/nagios-4.4.5

- name: compile nagios make clean
  make:
    chdir: /tmp/nagios-4.4.5
    target: clean

- name: nagios make all
  make:
    target: all
    chdir: /tmp/nagios-4.4.5

- name: compile nagios make install
  make:
    target: install
    chdir: /tmp/nagios-4.4.5

- name: nagios make init
  make:
    target: install-init
    chdir: /tmp/nagios-4.4.5

- name: compile nagios install config
  make:
    target: install-config
    chdir: /tmp/nagios-4.4.5

- name: compile nagios install commandmode
  make:
    target: install-commandmode
    chdir: /tmp/nagios-4.4.5

- name: interface installer
  make:
    target: install-webconf
    chdir: /tmp/nagios-4.4.5

- name: add user account
  htpasswd:
    path: /usr/local/nagios/etc/htpasswd.users
    name: "{{ username }}"
    password: "{{ password }}"

- name: a2enmod cgi
  command: a2enmod cgi

- name: restart apache2
  service:
    name: apache2
    state: restarted
