---
# tasks file for roles/grafana-1
- name: download package grafana
  apt:
    deb: https://dl.grafana.com/oss/release/grafana_7.3.6_amd64.deb
  register: pkg_grafana

- name: unpack grafana
  dpkg_selections:
    name: grafana_7.3.6_amd64.deb
    selection: install
  when: pkg_grafana.changed

- name: install libfconfig
  apt:
    name: libfontconfig1
    state: latest
    update_cache: yes

- name: install grafana
  apt:
    name: grafana
    state: latest
    update_cache: yes

- name: start and enable grafana
  service:
    name: grafana-server
    state: started
    enabled: yes

- name: install prometheus
  apt:
    name: prometheus
    state: latest
    update_cache: yes

- name: start prometheus
  service:
    name: prometheus
    state: started
    enabled: yes

- name: add influx key
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present

- name: add influxdate repo
  apt_repository:
    repo: 'deb https://repos.influxdata.com/ubuntu focal stable'
    state: present

- name: install telegraf
  apt:
    name: telegraft
    state: latest
    update_cache: yes

- name: start telegraf
  service:
    name: telegraf
    state: started
